version: "3.8"

services:
    php:
      build:
        dockerfile: docker/php/Dockerfile
      volumes:
        - .:/app

    nginx:
      image: nginx:1.25.0
      ports:
        - 80:80
      volumes:
        - .:/app
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php




