<?php

namespace ContainerXIrSSFX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ml0pg0sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ml0pg0s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ml0pg0s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'DTO' => ['privates', 'App\\DTO\\Request\\PriceDTO', 'getPriceDTOService', true],
        ], [
            'DTO' => 'App\\DTO\\Request\\PriceDTO',
        ]);
    }
}
