<?php

namespace ContainerXIrSSFX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExceptionEventListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ExceptionEventListener' shared autowired service.
     *
     * @return \App\EventListener\ExceptionEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/ExceptionEventListener.php';

        return $container->privates['App\\EventListener\\ExceptionEventListener'] = new \App\EventListener\ExceptionEventListener(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
