<?php

namespace ContainerXIrSSFX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPriceDTOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\Request\PriceDTO' shared autowired service.
     *
     * @return \App\DTO\Request\PriceDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DTO/DTOResolvedInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DTO/Request/PriceDTO.php';

        return $container->privates['App\\DTO\\Request\\PriceDTO'] = new \App\DTO\Request\PriceDTO();
    }
}
