<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIrSSFX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIrSSFX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIrSSFX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIrSSFX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXIrSSFX\App_KernelDevDebugContainer([
    'container.build_hash' => 'XIrSSFX',
    'container.build_id' => '417b9f4f',
    'container.build_time' => 1718921065,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIrSSFX');
