<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'price' => [[], ['_controller' => 'App\\Controller\\PriceController::index'], [], [['text', '/api/price']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    'App\Controller\PriceController::index' => [[], ['_controller' => 'App\\Controller\\PriceController::index'], [], [['text', '/api/price']], [], [], []],
];
